### ISSUE TITLE
Checking for new version crashes program

### ISSUE THREAD

**Issue by qwetboy10** [NetSparkleUpdater/NetSparkle#114] opened 2020-07-07 20:38 UTC
I'm using WPF with .net core 3.1 and NetSparkleUpdater.UI.WPF version 2.0.0-preview20200628002. When I manually check for updates with `CheckForUpdatesAtUserRequest();` my app crashes hard (Trying to open the visual studio just in time debugger doesn't work / the WPF DispatcherUnhandledException event doesn't fire). I initialize the sparkle object with the below code:
```csharp
sparkle = new SparkleUpdater(
                    "https://domain.com/Appcast/appcast.xml",
                    new Ed25519Checker(SecurityMode.Strict,
                        "base 64 private key") 
                ) {
                    UIFactory = new NetSparkleUpdater.UI.WPF.UIFactory(null)
                };
                sparkle.StartLoop(true)
```
Do you know what could cause this problem?

**Comment by qwetboy10** [comment] 2020-07-07 20:42
Catching the error with a try/catch also doesn't work by the way.

**Comment by Deadpikle** [comment] 2020-07-07 23:10
Hi @qwetboy10!

Thanks for your report. Unfortunately, I'm unable to replicate it using the samples on my end (same version of .NET Core and WPF). Can you provide any more details, please? 

* Able to run your app from Visual Studio debug mode to catch the exception there?
* Are you sure the issue is with NetSparkle and not something else that's going on?
* Have you looked in Window's Event Viewer app (https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/) for the crash there? You should see something under Windows Logs -> Application for your app.
* Can you try downloading this repo and running the samples with your URL and private key to see if you can replicate the bug with the sample?

Thanks!

**Comment by qwetboy10** [comment] 2020-07-08 17:17
Also, the WPF examples work without crashing. It says something about how the server is having a problem, but I'm just assuming that's because I didn't set my appcast up right.

**Comment by Deadpikle** [comment] 2020-07-10 23:07
> Running the code in Visual Studio debug mode caught the exception, it's saying something about how the calling thread must be STA. However, I have the STAThread attribute on my main method, and check for updates is called from an event handler for a button, so I'm not sure what the problem is. Is the fact that I have a custom entry point for my app possibly the problem?

Hmm....I will try to debug more on Sunday my time, but can you try setting `SparkleUpdater.ShowsUIOnMainThread` to `true` before calling `StartLoop`?

**Comment by Deadpikle** [comment] 2020-07-12 22:16
I spent some time trying to reproduce this without success. Please provide a full stack trace and/or a reproducible sample so I can look into it more, and please also try the `ShowsUIOnMainThread` property; otherwise, I'm really not able to pinpoint what the issue is. Thanks!

**Comment by Deadpikle** [comment] 2020-07-12 22:25
> 
> 
> Also, the WPF examples work without crashing. It says something about how the server is having a problem, but I'm just assuming that's because I didn't set my appcast up right.

Yes, that's likely the case -- check the `ILogger` (debug/console/output log) output as needed to help debug this.

**Comment by qwetboy10** [comment] 2020-07-16 17:09
ShowsUIOnMainThread = true fixed the issue for me. Thanks for the help. Here is a full stack trace though in case you wanted to know what was causing the issue.
```System.InvalidOperationException
  HResult=0x80131509
  Message=The calling thread must be STA, because many UI components require this.
  Source=PresentationCore
  StackTrace:
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.InputManager.get_Current()
   at System.Windows.Input.KeyboardNavigation..ctor()
   at System.Windows.FrameworkElement.FrameworkServices..ctor()
   at System.Windows.FrameworkElement.EnsureFrameworkServices()
   at System.Windows.FrameworkElement..ctor()
   at System.Windows.Controls.Control..ctor()
   at System.Windows.Window..ctor()
   at NetSparkleUpdater.UI.WPF.MessageNotificationWindow..ctor(MessageNotificationWindowViewModel viewModel)
   at NetSparkleUpdater.UI.WPF.UIFactory.ShowMessage(String title, String message)
   at NetSparkleUpdater.UI.WPF.UIFactory.ShowCannotDownloadAppcast(String appcastUrl)
   at NetSparkleUpdater.SparkleUpdater.<>c__DisplayClass136_0.<CheckForUpdatesAtUserRequest>b__0()
   at NetSparkleUpdater.SparkleUpdater.<>c__DisplayClass141_0.<CallFuncConsideringUIThreads>b__0(Object state)
   at System.Threading.SynchronizationContext.<>c.<Post>b__12_0(ValueTuple`2 s)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback`1.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()```

**Comment by qwetboy10** [comment] 2020-07-16 17:48
Actually, I ran into this issue another time. Turns out that it started crashing again once I fixed my appcast. Its a little weird.

- ShowsUIOnMainThread = false, Bad Appcast -> Crash
- ShowsUIOnMainThread = false, Bad Appcast -> Crash- ShowsUIOnMainThread = false, Bad Appcast -> Crash

**Comment by Deadpikle** [comment] 2020-07-16 22:57
Yeah, that stacktrace is helpful. I can fix that problem. Any other stack traces that are different (e.g. `ShowsUIOnMainThread = true, GoodAppcast -> Crash`) would be helpful. Thank you for the trace.

**Comment by Deadpikle** [comment] 2020-07-26 15:56
Can you please post or figure our a way to create a reproducible sample for your error? I'm not able to replicate, still, and the stack trace you posted above didn't lead me to the error cause. If you've got `ShowsUIOnMainThread = true`, then the callback is called on whatever thread initially called `CheckForUpdatesAtUserRequest`. Are you running that method on a background/non-STA thread? (https://stackoverflow.com/a/2330311/3938401)

Are you calling _any_ `SparkleUpdater` methods from a background thread? 

It's possible the app cast issues are caused by the bug reported in #119, too, so please try the latest dev version (2.0.0-preview20200726001) that fixes that issue.

**Comment by Deadpikle** [comment] 2020-08-23 22:26
@qwetboy10 Have you been able to try the latest version? Is this issue still happening?

**Comment by Deadpikle** [comment] 2020-11-08 20:50
@qwetboy10 Any updates? It's been almost 4 months since your last reply.

**Comment by qwetboy10** [comment] 2020-11-08 21:26
Sorry for not responding. I no longer work at the company where the bug happened, so I no longer have access to the code. Sorry I couldn't be more helpful.

**Comment by Deadpikle** [comment] 2020-11-08 21:27
No problem. I'll go ahead and close this as hopefully it's fixed. If you ever run into it again or hear from the company that they are running into the bug, feel free to comment and/or re-open. Thanks for responding! :)

**Closed by Deadpikle** 2020-11-08 21:27 UTC
Labels: awaiting feedback, bug

**Comment by OCJvanDijk** [comment] 2021-08-03 13:00
I was running into the exact same errors using NetSparkle with WPF.
Turns out the problem was I was creating `SparkleUpdater` before calling `App.Run()`.
`SparkleUpdater`'s constructor will store `SynchronizationContext.Current`, however at that point it won't be properly initialized to WPF's `SynchronizationContext`.

Maybe this could help someone in the future.
