### ISSUE TITLE
Auto Update For WPF .NET Core

### ISSUE THREAD

**Issue by aekoksalArg** [NetSparkleUpdater/NetSparkle#374] opened 2022-10-07 12:24 UTC
I developed a WPF application for my client. Software is running on multiple PCs and need an update system. I tried to use NetSparkle but seems like it is only for manuel update. My client can't update every single software manually. So I need to update software automatically or some kind of send update trigger from web. Is there any way to do that?

**Comment by Deadpikle** [comment] 2022-10-10 12:16
Hi @aekoksalArg,

 NetSparkle does allow for automatic update checks and even allows for automatic installs of those updates and/or prompting the user to install the updates. That's what the `startLoop()` call does. See https://github.com/NetSparkleUpdater/NetSparkle/blob/5859687adda7af71fce45f8a0b95e3d3f930fc5e/src/NetSparkle.Samples.NetCore.WPF/MainWindow.xaml.cs#L49

And https://github.com/NetSparkleUpdater/NetSparkle/blob/5859687adda7af71fce45f8a0b95e3d3f930fc5e/src/NetSparkle/SparkleUpdater.cs#L451-L459

And https://github.com/NetSparkleUpdater/NetSparkle/blob/develop/src/NetSparkle/SparkleUpdater.cs#L1886

Now, if that's broken at some point, that's one thing, but even without that feature, you can always add something like this to your own code to run your own automatic update checks by running some code every minute/30 minutes/etc.: https://stackoverflow.com/questions/38454349/checking-time-in-every-minute-in-c-sharp

**Comment by Deadpikle** [comment] 2023-06-04 18:26
@aekoksalArg Any other updates on your end, here?

You may also find https://github.com/NetSparkleUpdater/NetSparkle/blob/develop/src/NetSparkle/Enums/UserInteractionMode.cs and the `UserInteractionMode` property on `SparkleUpdater` helpful. This would allow you to automatically download (and even install) updates as needed.

If you don't respond soon, I'll close this issue, since I'm not sure what the problem is here and the library already features the things it seems like you are requesting. :-) Please let me know.

**Comment by Deadpikle** [comment] 2023-07-04 21:38
Closing due to original author not clarifying their needs and the fact that auto-download-and-install is available through `UserInteractionMode`. Please reopen, comment, or file a new issue if this is incorrect. Thanks!

**Closed as completed by Deadpikle** 2023-07-04 21:38 UTC
Labels: question, waiting for author response
