### ISSUE TITLE
DownloadHadError hook is not working in Windows Operating system

### ISSUE THREAD

**Issue by balaji222528** [NetSparkleUpdater/NetSparkle#616] opened 2024-09-09 19:43 UTC
DownloadHadError event is not working and not triggering in windows operating system when there is no connectivity etc.
But this is working in MAC which is quite wierd.

**Comment by Deadpikle** [comment] 2024-09-11 06:58
Hi @balaji222528,

Thanks for your report. I appreciate it. 

Just to be clear, what version of the library are you using on Windows, and what version of .NET are you using?

Thanks!

**Comment by balaji222528** [comment] 2024-09-11 12:17
Iam using .net 8 and netsparkle 2.3.0

**Comment by Deadpikle** [comment] 2024-09-14 12:10
@balaji222528 

On 2.3.0:

The docs for this event say, `Called when the download of an app cast file **has downloaded** but has an error other than corruption` (emphasis mine). In other words, if the app cast file never downloads, this event is not guaranteed to be called.

This event is not meant to be triggered when there is no download at all. Furthermore, I cannot replicate the `DownloadHadError` event being called on 2.3.0 on macOS.

If you are getting here through a call to `CheckForUpdatesQuietly`, monitor the `UpdateCheckFinished` event. The status will be `UpdateStatus.CouldNotDetermine` if the download failed outright.

If you are getting here through a call to `CheckForUpdatesAtUserRequest`, `UIFactory?.ShowCannotDownloadAppcast` is called.

If this does not help, please upload a reproducible sample.

Thanks!

**Comment by Deadpikle** [comment] 2024-12-25 03:53
Since 3.0 is officially out, and I didn't hear back from you about 2.3, I'm going to go ahead and close this as it should be resolved. Please comment or open a new issue if there are continued problems. Thanks!! :)

**Closed as completed by Deadpikle** 2024-12-25 03:53 UTC
Labels: research, waiting for author response
