### ISSUE TITLE
I don't get any log output from LogWriter

### ISSUE THREAD

**Issue by Byolock** [NetSparkleUpdater/NetSparkle#165] opened 2021-03-05 11:50 UTC
Im trying to enable the debug output from NetSparkle however I don't get any output to the Visual Studio Console:

My Application is a .Net 5.0 WPF UI Application.
This is my Code :

```
       private void Button_Click_1(object sender, RoutedEventArgs e)
        {
            _sparkle = new SparkleUpdater("https://somurl.com/appcast.xaml", new Ed25519Checker(SecurityMode.Unsafe, "base_64_public_key"))
            {
                UIFactory = new NetSparkleUpdater.UI.WPF.UIFactory(null),
                LogWriter = new LogWriter(true),
                ShowsUIOnMainThread = true,
                
            };
            _sparkle.StartLoop(true, true);
        }
```

If I hit this button I get the popup with my custom changelog and the download, skip  and so on buttons.
If I hit "download / install" button the downloading window appears but never makes any progress.
Nevertheless NetSparkle works up to the downloading windows so I should get some LogOutput but the only thing that is printed to the VisualStudio Console is : 

```
"UserForge.exe" (CoreCLR: clrhost): "C:\Users\lkohl\source\repos\UserForge\UserForge\bin\Debug\net5.0-windows10.0.18362.0\NetSparkle.dll" geladen. 
"UserForge.exe" (CoreCLR: clrhost): "C:\Users\lkohl\source\repos\UserForge\UserForge\bin\Debug\net5.0-windows10.0.18362.0\NetSparkle.UI.WPF.dll" geladen. 
```

I also tried `LogWriter = new LogWriter(false),` but this didn't change anything.

What could I try to get any log output?

**Comment by Deadpikle** [comment] 2021-03-07 15:34
Hi @Byolock, I'm sorry for the slow reply.

I'm not sure why you are not seeing any log output. When using the WPF sample (adjusted to run on .NET 5), I tried the following code: 

```csharp
private void ManualUpdateCheck_Click(object sender, RoutedEventArgs e)
        {
            _sparkle = new SparkleUpdater("https://netsparkleupdater.github.io/NetSparkle/files/sample-app/appcast.xml", 
                new Ed25519Checker(SecurityMode.Unsafe, "base_64_public_key"))
            {
                UIFactory = new NetSparkleUpdater.UI.WPF.UIFactory(null),
                LogWriter = new LogWriter(true),
                ShowsUIOnMainThread = true,
            };
            _sparkle.StartLoop(true, true);
            //await _sparkle.CheckForUpdatesAtUserRequest();
        }
```

I was able to view the console output. It also worked with `new LogWriter(false)`.

![print-diagnostic](https://user-images.githubusercontent.com/5092399/110245075-ce85d580-7f2f-11eb-89e4-5ed63459a22b.gif)

Are you sure your console/debug output isn't being redirected anywhere? You could also try implementing your own class that implements the `ILogger` interface and pass that to `SparkleUpdater` instead to verify that things are being passed to the `PrintMessage` method.

As far as the not downloading goes, the log will be helpful. You can also try setting `ShowsUIOnMainThread` to `false` as a test.

**Comment by Byolock** [comment] 2021-03-09 14:08
I am still analyzing this problem.

My current intermediate state is as follows: I have test set up a .Net Framework 4.8 project on another pc with the exact same code and get extensive debug output. So far so good.

This meant it must be either my settings in the IDE, other settings on the PC or differences between .Net Framework 4.8 and .Net 5.

The next step was then to repeat everything exactly as before only with .Net 5. This time I again got no debug output. Also .Net Core 3.1 as framework seems to cause this error for me.

My procedure was as follows : 

1. I opened Visual Studio 2019.
2. Created a new WPF App (.NET) project.
3. Manage nuget packages 
4. installed last preview version of NetSparkle.New and NetSparkleUpdater.UI.WPF (2.0.0-preview20210131001 at this time)
5. Put a button on the form
6. Created the OnClick event of the button
7. Pasted your code into the OnClick event
```
   _sparkle = new SparkleUpdater("https://netsparkleupdater.github.io/NetSparkle/files/sample-app/appcast.xml", 
                new Ed25519Checker(SecurityMode.Unsafe, "base_64_public_key"))
            {
                UIFactory = new NetSparkleUpdater.UI.WPF.UIFactory(null),
                LogWriter = new LogWriter(true),
                ShowsUIOnMainThread = true,
            };
            _sparkle.StartLoop(true, true);
            //await _sparkle.CheckForUpdatesAtUserRequest();
```
8. Pasted `private SparkleUpdater _sparkle;`
9. added imports : 
```
using NetSparkleUpdater;
using NetSparkleUpdater.Enums;
using NetSparkleUpdater.SignatureVerifiers;
```
10. start application
11. hit the button
12. No Log Output visible
13. NetSparkle Update Window Appears

Do you see any possible error in my workflow?

And no worries about your response time, as you can see I am just as quick as you are and you've got far more issues to work on. Im thankful for any help.

**Comment by Byolock** [comment] 2021-03-10 07:40
I forgot something : after the second step I had to change the Framework to .Net 5 as It defaults to .Net Core 3.

**Comment by Deadpikle** [comment] 2021-03-14 18:38
@Byolock I can replicate your issue, using the steps you provided. Thank you!

I think the issue is a bit complex:

1. When debugging your own application, the VS window shows `Debug.WriteLine`, not `Console.WriteLine`, so `new LogWriter(true)` won't work as that uses `Console.WriteLine`
2. When using NuGet, you're getting a release build, so the `Debug.WriteLine` calls from `NetSparkleUpdater.LogWriter` do nothing because it's a release build.
3. Because of this, `LogWriter` essentially becomes useless when debugging your own app. Whoops.

The fix is for `LogWriter` to use `Trace.WriteLine` instead of `Debug.WriteLine`, which should enable viewing the debug lines from other apps.

Fix for this is available in `2.0.0-preview20210314001`.

**Comment by Deadpikle** [comment] 2021-03-15 01:07
Reopening because `Trace.WriteLine` didn't fix it somehow. Needs more investigation.

**Comment by Deadpikle** [comment] 2021-03-15 01:11
![Screenshot 2021-03-14 211104](https://user-images.githubusercontent.com/5092399/111091589-d0403200-8509-11eb-96db-c81d267d4df9.png)

Bother. I didn't check to make sure it was enabled.

**Closed** 2021-03-15 01:17 UTC
Labels: bug, help wanted

**Comment by Deadpikle** [comment] 2021-03-15 02:06
OK, I'm getting console output in VS with `LogWriter = new LogWriter(false)` now. Fixed.
